import './ShapeTest.js';
import './LineTest.js';
import './RectangleTest.js';
import './PointTest.js';
import './BoxTest.js';
import './BoardTest.js';
import './LayersTest.js';
import './PieceTest.js';
import './QueenTest.js';